package com.bypassnext.release

import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

class RootUtilTest {

    @Test
    fun testGetDisablePrivacyScript() {
        val tempDir = "/data/local/tmp/filtered_certs"
        val script = RootUtil.getDisablePrivacyScript(tempDir)

        // Verify key commands are present in the script
        assertTrue("Script should reset private_dns_mode", script.contains("settings put global private_dns_mode off"))
        assertTrue("Script should delete private_dns_specifier", script.contains("settings delete global private_dns_specifier"))
        assertTrue("Script should unmount certificates", script.contains("umount"))
        // Expect quotes around the path as generated by the script
        assertTrue("Script should clean up temp directory", script.contains("rm -rf \"$tempDir\""))
        assertTrue("Script should include a success message", script.contains("Privacy Mode Deactivated"))
    }

    @Test
    fun testCheckPrivacyStatus_Enabled() {
        val dnsMode = "hostname"
        val dnsSpecifier = "a4f5f2.dns.nextdns.io"
        assertTrue("Should return true when DNS mode is hostname and specifier matches NextDNS ID",
            RootUtil.checkPrivacyStatus(dnsMode, dnsSpecifier))
    }

    @Test
    fun testCheckPrivacyStatus_Disabled() {
        val dnsMode = "off"
        val dnsSpecifier = ""
        assertFalse("Should return false when DNS mode is off",
            RootUtil.checkPrivacyStatus(dnsMode, dnsSpecifier))
    }

    @Test
    fun testCheckPrivacyStatus_WrongMode() {
        val dnsMode = "private"
        val dnsSpecifier = "a4f5f2.dns.nextdns.io"
        assertFalse("Should return false when DNS mode is not hostname",
            RootUtil.checkPrivacyStatus(dnsMode, dnsSpecifier))
    }

    @Test
    fun testCheckPrivacyStatus_WrongSpecifier() {
        val dnsMode = "hostname"
        val dnsSpecifier = "google.com"
        assertFalse("Should return false when DNS specifier is not NextDNS ID",
            RootUtil.checkPrivacyStatus(dnsMode, dnsSpecifier))
    }

    @Test
    fun testCheckPrivacyStatus_EmptyInputs() {
        assertFalse("Should return false for empty inputs",
            RootUtil.checkPrivacyStatus("", ""))
    }

    @Test
    fun testCheckPrivacyStatus_WithWhitespace() {
        // Note: The caller (isPrivacyModeEnabled) is responsible for trimming,
        // so checkPrivacyStatus expects exact matches.
        // If we pass whitespace, it should fail.
        val dnsMode = "hostname "
        val dnsSpecifier = "a4f5f2.dns.nextdns.io"
        assertFalse("Should return false if inputs contain whitespace (caller trims)",
            RootUtil.checkPrivacyStatus(dnsMode, dnsSpecifier))
    }
}
